language: android
android:
  components:
     - tools
     - platform-tools
     - android-30
     - build-tools-30.0.0

branches:
  only:
    - master

after_success:
- ./gradlew test

before_install:
  - yes | sdkmanager "platforms;android-30"